services:
  app:
    image: php:8.3-fpm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      database:
        condition: service_healthy

  web:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  # db:
  #   image: postgres:18
  #   environment:
  #     POSTGRES_ROOT_PASSWORD: root
  #     POSTGRES_DATABASE: budget_tracker
  #     POSTGRES_USER: symfony
  #     POSTGRES_PASSWORD: symfony
  #   ports:
  #     - "3306:3306"
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-18}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-symfony}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql:rw
    ports:
      - "${POSTGRES_PORT:-3306}:3306"

volumes:
  database_data: